spring:
  application:
    name: springcloud-getway-server
  cloud:
    gateway:
      routes:
        - id: test
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/test/**